export const KNOWN_STATION_NAMES = [
  'Trikotschätze',
  'Jüdischer Fußball',
  'Professionalisierung / Kicker-Archiv',
  'DFL-Lounge',
  'Fussball und Medien',
  'Fußball und Medien: Fernsehformate',
  'Spielfeld',
  'Balltempel - Rondell',
  'Balltempel',
  'Balltempel - Adidas',
  'Kino',
  'Geschichte des DFB',
  'Frauenfußball',
  'DFB Pokal',
  'Europäische Pokalwettbewerbe',
  'Fans',
  'Schiedsrichter',
  'Hall of Fame',
  'Trainer und Taktik',
  'Bundesliga Vorgeschichte',
  'Schatzkammer',
  'Bundesliga Dekaden',
  'Wunder vom Bern',
  'DFB',
  'DDR',
  'Technikraum',
  'Magische Momente I',
  'Magische Momente II',
  'Golden Generation',
  'Bundesliga Karussell'
].sort((a, b) => a.localeCompare(b, 'de'))
